//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEExpress.Models
{
    using System;
    
    public partial class spCuadre
    {
        public string Usuario { get; set; }
        //public Nullable<System.Guid> idfactura { get; set; }
       // public string factura { get; set; }
        public string Cliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string Moneda { get; set; }
        public decimal Efectivo { get; set; }
        public decimal Tarjeta { get; set; }
        public decimal Cheque { get; set; }
        public decimal Otros { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public decimal Recibos { get; set; }
    }
}
